[build-system]
requires = ["setuptools>=50.3.2", "setuptools_scm[toml]>=3.4"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "saltpylint/version.py"
write_to_template = "# pylint: skip-file\n\n__version__ = \"{version}\"\n"
